// redux/actions/contratos/types.js
export const FETCH_CONTRATOS_REQUEST = "FETCH_CONTRATOS_REQUEST";
export const FETCH_CONTRATOS_SUCCESS = "FETCH_CONTRATOS_SUCCESS";
export const FETCH_CONTRATOS_FAILURE = "FETCH_CONTRATOS_FAILURE";

export const FETCH_CONTRATO_ONE_SUCCESS = "FETCH_CONTRATO_ONE_SUCCESS";
export const FETCH_CONTRATO_ONE_FAILURE = "FETCH_CONTRATO_ONE_FAILURE";
